add command to list tags of repo

diff --git a/bin/dockerhubapi b/bin/dockerhubapi
--- a/bin/dockerhubapi
+++ b/bin/dockerhubapi
@@ -104,6 +104,21 @@ elif [[ "$1" = "info" ]]; then
     -H "Authorization:JWT $(cat ${jwt_file})" \
     "https://hub.docker.com/v2/repositories/${dockerhub_namespace}/${dockerhub_repo_name}/"
 
+elif [[ "$1" = "tags" ]]; then
+  shift
+  dockerhub_repo_name="$1";shift; [[ -z "$dockerhub_repo_name" ]] && { echo "parameter missing" >&2; exit 1; }
+  : ${page:="1"}
+  result="$(curl -s \
+    -H "Authorization:JWT $(cat ${jwt_file})" \
+    "https://hub.docker.com/v2/repositories/${dockerhub_namespace}/${dockerhub_repo_name}/tags/?page=${page}&page_size=10000"
+  )"
+  if [[ $short_output -eq 1 ]];then
+    echo "$result" \
+      | jq -r '.results|sort_by(.last_updated)|map(.name)[]' 
+  else
+    echo "$result"
+  fi
+
 elif [[ "$1" = "catalog" ]]; then
   shift
   curl -i \
