can CRD links for dockerhub repos

diff --git a/bin/dockerhubapi b/bin/dockerhubapi
--- a/bin/dockerhubapi
+++ b/bin/dockerhubapi
@@ -169,6 +169,38 @@ elif [[ "$1" = "repogroups" ]]; then
     -H "Accept: application/json" \
     "https://hub.docker.com/v2/repositories/${dockerhub_namespace}/${dockerhub_repo_name}/groups/"
 
+elif [[ "$1" = "link-list" ]]; then
+  shift
+  dockerhub_repo_name="$1";shift; [[ -z "$dockerhub_repo_name" ]] && { echo "parameter missing" >&2; exit 1; }
+  curl -s \
+    -H "Authorization:JWT $(cat ${jwt_file})" \
+    "https://hub.docker.com/v2/repositories/${dockerhub_namespace}/${dockerhub_repo_name}/links/" \
+    | jq '.'
+
+elif [[ "$1" = "link-add" ]]; then
+  shift
+  dockerhub_repo_name="$1";shift; [[ -z "$dockerhub_repo_name" ]] && { echo "parameter missing" >&2; exit 1; }
+  linked_repo="$1";shift; [[ -z "$linked_repo" ]] && { echo "parameter missing" >&2; exit 1; }
+
+  if [[ ! "${linked_repo}" =~ ^[^/]*/[^/]*$ ]];then
+    linked_repo="${dockerhub_namespace}/${linked_repo}"
+  fi
+  curl -s \
+    -H "Authorization:JWT $(cat ${jwt_file})" \
+    -X POST \
+    -H "Content-Type:application/json" \
+    --data-binary "{\"to_repo\":\"${linked_repo}\"}" \
+    "https://hub.docker.com/v2/repositories/${dockerhub_namespace}/${dockerhub_repo_name}/links/"
+
+elif [[ "$1" = "link-del" ]]; then
+  shift
+  dockerhub_repo_name="$1";shift; [[ -z "$dockerhub_repo_name" ]] && { echo "parameter missing" >&2; exit 1; }
+  linked_id="$1";shift; [[ -z "$linked_id" ]] && { echo "parameter missing" >&2; exit 1; }
+  curl -s \
+    -H "Authorization:JWT $(cat ${jwt_file})" \
+    -X DELETE \
+    "https://hub.docker.com/v2/repositories/${dockerhub_namespace}/${dockerhub_repo_name}/links/${linked_id}/"
+
 elif [[ "$1" = "addgroup" ]]; then
   shift
   dockerhub_repo_name="$1";shift; [[ -z "$dockerhub_repo_name" ]] && { echo "parameter missing" >&2; exit 1; }
