foo bar

diff --git a/bin/dockerhubapi b/bin/dockerhubapi
--- a/bin/dockerhubapi
+++ b/bin/dockerhubapi
@@ -137,6 +137,24 @@ elif [[ "$1" = "build" ]]; then
     --data-binary '{"source_name":"master","source_type":"Branch","dockerfile_location":"/"}' \
     "https://hub.docker.com/v2/repositories/${dockerhub_namespace}/${dockerhub_repo_name}/autobuild/trigger-build/"
 
+elif [[ "$1" = "history" ]]; then
+  shift
+  dockerhub_repo_name="$1";shift; [[ -z "$dockerhub_repo_name" ]] && { echo "parameter missing" >&2; exit 1; }
+  curl -s \
+    -H "Authorization:JWT $(cat ${jwt_file})" \
+    "https://hub.docker.com/v2/repositories/${dockerhub_namespace}/${dockerhub_repo_name}/buildhistory/"
+
+elif [[ "$1" = "buildcode" ]]; then
+  shift
+  dockerhub_repo_name="$1";shift; [[ -z "$dockerhub_repo_name" ]] && { echo "parameter missing" >&2; exit 1; }
+  build_id="$1";shift; [[ -z "$build_id" ]] && { echo "parameter missing" >&2; exit 1; }
+  curl -s \
+    -H "Authorization:JWT $(cat ${jwt_file})" \
+    "https://hub.docker.com/v2/repositories/${dockerhub_namespace}/${dockerhub_repo_name}/buildhistory/${build_id}/"
+
+# https://hub.docker.com/v2/repositories/nasoym/bss_automation_demo/buildhistory/?page_size=100
+# https://hub.docker.com/v2/repositories/nasoym/bss_automation_demo/buildhistory/b7qdkq6s3dcn2qvvn4euwmt/
+
 elif [[ "$1" = "listgroups" ]]; then
   shift
   curl -s \
